/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Script */

#ifndef _Included_Script
#define _Included_Script
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Script
 * Method:    createUnit
 * Signature: (I)LUnit;
 */
JNIEXPORT jobject JNICALL Java_Script_createUnit
  (JNIEnv *, jclass, jint);

/*
 * Class:     Script
 * Method:    destroyUnit
 * Signature: (LUnit;)V
 */
JNIEXPORT void JNICALL Java_Script_destroyUnit
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
