/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class QueryPerformanceCounter */

#ifndef _Included_QueryPerformanceCounter
#define _Included_QueryPerformanceCounter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     QueryPerformanceCounter
 * Method:    nativeQueryPerformanceFrequency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_QueryPerformanceCounter_nativeQueryPerformanceFrequency
  (JNIEnv *, jclass);

/*
 * Class:     QueryPerformanceCounter
 * Method:    nativeQueryPerformanceCounter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_QueryPerformanceCounter_nativeQueryPerformanceCounter
  (JNIEnv *, jclass);

/*
 * Class:     QueryPerformanceCounter
 * Method:    nativeShowInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_QueryPerformanceCounter_nativeShowInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
