/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UnsafeNativeUtil */

#ifndef _Included_UnsafeNativeUtil
#define _Included_UnsafeNativeUtil
#ifdef __cplusplus
extern "C" {
#endif
#undef UnsafeNativeUtil_SEEK_SET
#define UnsafeNativeUtil_SEEK_SET 0L
#undef UnsafeNativeUtil_SEEK_CUR
#define UnsafeNativeUtil_SEEK_CUR 1L
#undef UnsafeNativeUtil_SEEK_END
#define UnsafeNativeUtil_SEEK_END 2L
/*
 * Class:     UnsafeNativeUtil
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_UnsafeNativeUtil_malloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     UnsafeNativeUtil
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_UnsafeNativeUtil_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     UnsafeNativeUtil
 * Method:    read
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_UnsafeNativeUtil_read
  (JNIEnv *, jclass, jlong);

/*
 * Class:     UnsafeNativeUtil
 * Method:    write
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_UnsafeNativeUtil_write
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     UnsafeNativeUtil
 * Method:    memcpy
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_UnsafeNativeUtil_memcpy
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     UnsafeNativeUtil
 * Method:    memset
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_UnsafeNativeUtil_memset
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     UnsafeNativeUtil
 * Method:    wrapbuf
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_UnsafeNativeUtil_wrapbuf
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     UnsafeNativeUtil
 * Method:    getbuf
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_UnsafeNativeUtil_getbuf
  (JNIEnv *, jclass, jobject);

/*
 * Class:     UnsafeNativeUtil
 * Method:    fopen
 * Signature: (Ljava/lang/String;Ljava/lang/String;)LFilePointer;
 */
JNIEXPORT jobject JNICALL Java_UnsafeNativeUtil_fopen
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     UnsafeNativeUtil
 * Method:    fclose
 * Signature: (LFilePointer;)I
 */
JNIEXPORT jint JNICALL Java_UnsafeNativeUtil_fclose
  (JNIEnv *, jclass, jobject);

/*
 * Class:     UnsafeNativeUtil
 * Method:    fread
 * Signature: (JIILFilePointer;)I
 */
JNIEXPORT jint JNICALL Java_UnsafeNativeUtil_fread
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     UnsafeNativeUtil
 * Method:    fwrite
 * Signature: (JIILFilePointer;)I
 */
JNIEXPORT jint JNICALL Java_UnsafeNativeUtil_fwrite
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     UnsafeNativeUtil
 * Method:    feof
 * Signature: (LFilePointer;)I
 */
JNIEXPORT jint JNICALL Java_UnsafeNativeUtil_feof
  (JNIEnv *, jclass, jobject);

/*
 * Class:     UnsafeNativeUtil
 * Method:    fseek
 * Signature: (LFilePointer;II)I
 */
JNIEXPORT jint JNICALL Java_UnsafeNativeUtil_fseek
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     UnsafeNativeUtil
 * Method:    ftell
 * Signature: (LFilePointer;)I
 */
JNIEXPORT jint JNICALL Java_UnsafeNativeUtil_ftell
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
