/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sample */

#ifndef _Included_Sample
#define _Included_Sample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sample
 * Method:    MyNativeFunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Sample_MyNativeFunction(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
