/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JoystickWin32Ex */

#ifndef _Included_JoystickWin32Ex
#define _Included_JoystickWin32Ex
#ifdef __cplusplus
extern "C" {
#endif
#undef JoystickWin32Ex_FIELD_ID_dwSize
#define JoystickWin32Ex_FIELD_ID_dwSize 0L
#undef JoystickWin32Ex_FIELD_ID_dwFlags
#define JoystickWin32Ex_FIELD_ID_dwFlags 4L
#undef JoystickWin32Ex_FIELD_ID_dwXpos
#define JoystickWin32Ex_FIELD_ID_dwXpos 8L
#undef JoystickWin32Ex_FIELD_ID_dwYpos
#define JoystickWin32Ex_FIELD_ID_dwYpos 12L
#undef JoystickWin32Ex_FIELD_ID_dwZpos
#define JoystickWin32Ex_FIELD_ID_dwZpos 16L
#undef JoystickWin32Ex_FIELD_ID_dwRpos
#define JoystickWin32Ex_FIELD_ID_dwRpos 20L
#undef JoystickWin32Ex_FIELD_ID_dwUpos
#define JoystickWin32Ex_FIELD_ID_dwUpos 24L
#undef JoystickWin32Ex_FIELD_ID_dwVpos
#define JoystickWin32Ex_FIELD_ID_dwVpos 28L
#undef JoystickWin32Ex_FIELD_ID_dwButtons
#define JoystickWin32Ex_FIELD_ID_dwButtons 32L
#undef JoystickWin32Ex_FIELD_ID_dwButtonNumber
#define JoystickWin32Ex_FIELD_ID_dwButtonNumber 36L
#undef JoystickWin32Ex_FIELD_ID_dwPOV
#define JoystickWin32Ex_FIELD_ID_dwPOV 40L
#undef JoystickWin32Ex_FIELD_ID_dwReserved1
#define JoystickWin32Ex_FIELD_ID_dwReserved1 44L
#undef JoystickWin32Ex_FIELD_ID_dwReserved2
#define JoystickWin32Ex_FIELD_ID_dwReserved2 48L
#undef JoystickWin32Ex_JOY_BUTTON1
#define JoystickWin32Ex_JOY_BUTTON1 1L
#undef JoystickWin32Ex_JOY_BUTTON2
#define JoystickWin32Ex_JOY_BUTTON2 2L
#undef JoystickWin32Ex_JOY_BUTTON3
#define JoystickWin32Ex_JOY_BUTTON3 4L
#undef JoystickWin32Ex_JOY_BUTTON4
#define JoystickWin32Ex_JOY_BUTTON4 8L
#undef JoystickWin32Ex_JOY_BUTTON5
#define JoystickWin32Ex_JOY_BUTTON5 16L
#undef JoystickWin32Ex_JOY_BUTTON6
#define JoystickWin32Ex_JOY_BUTTON6 32L
#undef JoystickWin32Ex_JOY_BUTTON7
#define JoystickWin32Ex_JOY_BUTTON7 64L
#undef JoystickWin32Ex_JOY_BUTTON8
#define JoystickWin32Ex_JOY_BUTTON8 128L
#undef JoystickWin32Ex_JOY_BUTTON9
#define JoystickWin32Ex_JOY_BUTTON9 256L
#undef JoystickWin32Ex_JOY_BUTTON10
#define JoystickWin32Ex_JOY_BUTTON10 512L
#undef JoystickWin32Ex_JOY_BUTTON11
#define JoystickWin32Ex_JOY_BUTTON11 1024L
#undef JoystickWin32Ex_JOY_BUTTON12
#define JoystickWin32Ex_JOY_BUTTON12 2048L
#undef JoystickWin32Ex_JOY_BUTTON13
#define JoystickWin32Ex_JOY_BUTTON13 4096L
#undef JoystickWin32Ex_JOY_BUTTON14
#define JoystickWin32Ex_JOY_BUTTON14 8192L
#undef JoystickWin32Ex_JOY_BUTTON15
#define JoystickWin32Ex_JOY_BUTTON15 16384L
#undef JoystickWin32Ex_JOY_BUTTON16
#define JoystickWin32Ex_JOY_BUTTON16 32768L
#undef JoystickWin32Ex_JOY_BUTTON17
#define JoystickWin32Ex_JOY_BUTTON17 65536L
#undef JoystickWin32Ex_JOY_BUTTON18
#define JoystickWin32Ex_JOY_BUTTON18 131072L
#undef JoystickWin32Ex_JOY_BUTTON19
#define JoystickWin32Ex_JOY_BUTTON19 262144L
#undef JoystickWin32Ex_JOY_BUTTON20
#define JoystickWin32Ex_JOY_BUTTON20 524288L
#undef JoystickWin32Ex_JOY_BUTTON21
#define JoystickWin32Ex_JOY_BUTTON21 1048576L
#undef JoystickWin32Ex_JOY_BUTTON22
#define JoystickWin32Ex_JOY_BUTTON22 2097152L
#undef JoystickWin32Ex_JOY_BUTTON23
#define JoystickWin32Ex_JOY_BUTTON23 4194304L
#undef JoystickWin32Ex_JOY_BUTTON24
#define JoystickWin32Ex_JOY_BUTTON24 8388608L
#undef JoystickWin32Ex_JOY_BUTTON25
#define JoystickWin32Ex_JOY_BUTTON25 16777216L
#undef JoystickWin32Ex_JOY_BUTTON26
#define JoystickWin32Ex_JOY_BUTTON26 33554432L
#undef JoystickWin32Ex_JOY_BUTTON27
#define JoystickWin32Ex_JOY_BUTTON27 67108864L
#undef JoystickWin32Ex_JOY_BUTTON28
#define JoystickWin32Ex_JOY_BUTTON28 134217728L
#undef JoystickWin32Ex_JOY_BUTTON29
#define JoystickWin32Ex_JOY_BUTTON29 268435456L
#undef JoystickWin32Ex_JOY_BUTTON30
#define JoystickWin32Ex_JOY_BUTTON30 536870912L
#undef JoystickWin32Ex_JOY_BUTTON31
#define JoystickWin32Ex_JOY_BUTTON31 1073741824L
#undef JoystickWin32Ex_JOY_BUTTON32
#define JoystickWin32Ex_JOY_BUTTON32 -2147483648L
#undef JoystickWin32Ex_JOY_AXISX
#define JoystickWin32Ex_JOY_AXISX 8L
#undef JoystickWin32Ex_JOY_AXISY
#define JoystickWin32Ex_JOY_AXISY 12L
#undef JoystickWin32Ex_JOY_AXISZ
#define JoystickWin32Ex_JOY_AXISZ 16L
#undef JoystickWin32Ex_JOY_AXISR
#define JoystickWin32Ex_JOY_AXISR 20L
#undef JoystickWin32Ex_JOY_AXISU
#define JoystickWin32Ex_JOY_AXISU 24L
#undef JoystickWin32Ex_JOY_AXISV
#define JoystickWin32Ex_JOY_AXISV 28L
#undef JoystickWin32Ex_JOY_RETURNX
#define JoystickWin32Ex_JOY_RETURNX 1L
#undef JoystickWin32Ex_JOY_RETURNY
#define JoystickWin32Ex_JOY_RETURNY 2L
#undef JoystickWin32Ex_JOY_RETURNZ
#define JoystickWin32Ex_JOY_RETURNZ 4L
#undef JoystickWin32Ex_JOY_RETURNR
#define JoystickWin32Ex_JOY_RETURNR 8L
#undef JoystickWin32Ex_JOY_RETURNU
#define JoystickWin32Ex_JOY_RETURNU 16L
#undef JoystickWin32Ex_JOY_RETURNV
#define JoystickWin32Ex_JOY_RETURNV 32L
#undef JoystickWin32Ex_JOY_RETURNPOV
#define JoystickWin32Ex_JOY_RETURNPOV 64L
#undef JoystickWin32Ex_JOY_RETURNBUTTONS
#define JoystickWin32Ex_JOY_RETURNBUTTONS 128L
#undef JoystickWin32Ex_JOY_RETURNRAWDATA
#define JoystickWin32Ex_JOY_RETURNRAWDATA 256L
#undef JoystickWin32Ex_JOY_RETURNPOVCTS
#define JoystickWin32Ex_JOY_RETURNPOVCTS 512L
#undef JoystickWin32Ex_JOY_RETURNCENTERED
#define JoystickWin32Ex_JOY_RETURNCENTERED 1024L
#undef JoystickWin32Ex_JOY_USEDEADZONE
#define JoystickWin32Ex_JOY_USEDEADZONE 2048L
#undef JoystickWin32Ex_JOY_RETURNALL
#define JoystickWin32Ex_JOY_RETURNALL 255L
#undef JoystickWin32Ex_JOYERR_NOERROR
#define JoystickWin32Ex_JOYERR_NOERROR 0L
#undef JoystickWin32Ex_JOYERR_UNPLUGGED
#define JoystickWin32Ex_JOYERR_UNPLUGGED 160L
#undef JoystickWin32Ex_MMSYSERR_BADDEVICEID
#define JoystickWin32Ex_MMSYSERR_BADDEVICEID 2L
#undef JoystickWin32Ex_MMSYSERR_NODRIVER
#define JoystickWin32Ex_MMSYSERR_NODRIVER 6L
#undef JoystickWin32Ex_MMSYSERR_INVALPARAM
#define JoystickWin32Ex_MMSYSERR_INVALPARAM 11L
#undef JoystickWin32Ex_AXIS_NORMALIZATION_FACTOR
#define JoystickWin32Ex_AXIS_NORMALIZATION_FACTOR 3.0518044E-5f
/* Inaccessible static: joyInfoStructs */
/* Inaccessible static: errors */
/*
 * Class:     JoystickWin32Ex
 * Method:    nativeWrapJoyInfoStruct
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_JoystickWin32Ex_nativeWrapJoyInfoStruct
  (JNIEnv *, jclass, jint);

/*
 * Class:     JoystickWin32Ex
 * Method:    nativePoll
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_JoystickWin32Ex_nativePoll
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     JoystickWin32Ex
 * Method:    nativeShowInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JoystickWin32Ex_nativeShowInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
